#!/bin/bash

# ---------------------------------------------------------
# SETUP PATHS
# ---------------------------------------------------------
# Get the directory where this script is physically located
SCRIPT_DIR=$(dirname "$(realpath "$0")")
PROJECT_ROOT="$SCRIPT_DIR/.."

# Path to the executable generated by 'make test-pg'
# (Assumes Makefile outputs 'test_playground' in the project root)
EXECUTABLE="$PROJECT_ROOT/test_playground"

# Where to find .IFJ25 files and where to put results
TEST_DIR="$SCRIPT_DIR/lexer"
OUTPUT_BASE="$SCRIPT_DIR/output/lexer"

# ---------------------------------------------------------
# 1. COMPILE THE C PROGRAM
# ---------------------------------------------------------
echo "------------------------------------------------"
echo "1. Compiling Project via Makefile..."

# -C tells make to change directory to PROJECT_ROOT before running
make -C "$PROJECT_ROOT" clean
make -C "$PROJECT_ROOT" compile-test

# Check if compilation worked (make returns non-zero on error)
if [ $? -ne 0 ]; then
    echo "[FATAL] Compilation failed."
    exit 1
fi

# Check if the executable actually exists after make
if [ ! -f "$EXECUTABLE" ]; then
    echo "[FATAL] Make finished, but '$EXECUTABLE' was not found."
    exit 1
fi

echo "[OK] Compilation successful."

# ---------------------------------------------------------
# 2. RUN TESTS
# ---------------------------------------------------------
echo "------------------------------------------------"
echo "2. Running Lexer Tests..."

# Ensure output directory exists
mkdir -p "$OUTPUT_BASE"

# Find all .IFJ25 files in the lexer folder recursively
find "$TEST_DIR" -name "*.IFJ25" | while read input_file; do
    
    # Extract category (parent folder name, e.g., 'strings')
    parent_dir=$(dirname "$input_file")
    category=$(basename "$parent_dir")
    
    # Extract filename without extension (e.g., 'str1')
    filename=$(basename "$input_file" .IFJ25)
    
    # Create specific output folder
    output_dir="$OUTPUT_BASE/$category"
    mkdir -p "$output_dir"
    
    # Define output file
    output_file="$output_dir/${filename}_output.txt"
    
    # -----------------------------------------------------
    # FORMATTING THE OUTPUT
    # -----------------------------------------------------
    
    # 1. Dump the content of the input file (the test case)
    echo "Input:" > "$output_file"
    cat "$input_file" >> "$output_file"
    
    # 2. Add a newline and the separator
    echo "" >> "$output_file"
    echo "===============================" >> "$output_file"
    echo "Output:" >> "$output_file"
    
    # 3. Run the C program: stdout -> file, stderr -> temp file
    # We capture stderr separately to append it conditionally
    stderr_tmp=$(mktemp)
    "$EXECUTABLE" "$input_file" >> "$output_file" 2> "$stderr_tmp"
    exit_code=$?
    
    # -----------------------------------------------------

    # 4. Check Logic: If Error (non-zero), append separator and stderr
    if [ $exit_code -ne 0 ]; then
        echo "" >> "$output_file"
        echo "===============================" >> "$output_file"
        echo "Exit Code: $exit_code" >> "$output_file"
        echo "Standard Error:" >> "$output_file"
        cat "$stderr_tmp" >> "$output_file"
        
        echo "[FAIL] Crashed/Error: $category/$filename (Exit: $exit_code)"
    else
        echo "[OK] $category/$filename"
    fi

    # Cleanup temp file
    rm "$stderr_tmp"

done

echo "------------------------------------------------"
echo "Done! Results saved in: $OUTPUT_BASE"