#ifndef ERROR_CODES_H
#define ERROR_CODES_H

/*===== Коды ошибок =====*/
typedef enum {
    LEXER_ERROR = 1,
    SYNTAX_ERROR = 2,
    SEMANTIC_ERROR_UNDEFINED = 3,
    SEMANTIC_ERROR_REDECLARATION = 4,
    SEMANTIC_ERROR_ARGUMENT = 5,      
    SEMANTIC_ERROR_TYPE_MISMATCH = 6,
    SEMANTIC_ERROR_OTHER = 10,
    RUNTIME_ERROR_INVALID_TYPE = 25,
    RUNTIME_ERROR_TYPE_MISMATCH = 26,
    INTERNAL_ERROR = 99
} ErrorCode;

#endif 
